name: Build and Deploy to Kubernetes

on:
  push:
    branches:
      - main  # Runs on push to main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/myapp:latest
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push  # Deploy only after the image is pushed

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Kubernetes CLI (kubectl)
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Authenticate with Kubernetes
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > kubeconfig.yaml
          export KUBECONFIG=kubeconfig.yaml

      - name: Update Kubernetes Deployment
        run: |
          kubectl set image deployment/myapp myapp=${{ secrets.DOCKER_USERNAME }}/myapp:latest --record
          kubectl rollout status deployment/myapp
